import { test, expect } from '@playwright/test';
import { resolve } from 'node:path';
import { readFile } from 'node:fs/promises';
import { createAnalysisRecord, parseAnalysisRecord, serializeAnalysisRecord, type AnalysisJson } from '../../core/src/analysis-result';
import { createServer as createViteServer, loadConfigFromFile, mergeConfig, type InlineConfig } from 'vite';

// Independent SciPy DOP853 values; not generated by the implementation under test.
// Columns: minutes, CFU/mL, PFU/mL, OD. Fixed initial conditions are set below.
const REFERENCE = [
  [0,10000000,100000,.0125],
  [5,10243365.688072033,93280.94372026029,.012816146192369622],
  [10,10491982.40966677,118586.96354245362,.013138809595028503],
  [15,10740933.441461252,202532.353341776,.013466940356537307],
  [20,10982460.908055,365671.1188761933,.013799402446191327],
  [25,11204799.851815766,652430.7256915687,.01413376437474343],
  [30,11387615.446612658,1159277.719087575,.014464934136778582],
  [40,11458833.99430788,3706946.7041725204,.015071362856815252],
  [50,10460237.0643752,12003115.608275421,.015408351601819774],
  [60,6980213.60355128,38230272.161794186,.014876257203690612],
  [70,1858838.6444297095,108981059.77823624,.012380732842506303],
  [80,68776.9335401689,230184889.17843506,.00790792915032959],
];
const CSV = 'timeMin,type,value,sigma\n' + REFERENCE.flatMap(([time,cfu,pfu,od]) =>
  [`${time},CFU,${cfu},.03`,`${time},PFU,${pfu},.03`,`${time},OD,${od},.001`]).join('\n');

test('growth observations reach real workers, verifiable fit exports and cancellable replay', async ({ page }, info) => {
  test.setTimeout(180000);
  const root = process.cwd(), fixtureId = resolve(root,'src/growth-fit-fixture.tsx');
  const loaded = await loadConfigFromFile({command:'serve',mode:'development'},resolve(root,'vite.config.ts'));
  if(!loaded) throw new Error('Could not load the real web application configuration');
  const server = await createViteServer(mergeConfig(loaded.config,{
    root,configFile:false,cacheDir:info.outputPath('vite-cache'),server:{host:'127.0.0.1',port:0,open:false},
    plugins:[{
      name:'growth-fit-fixture',
      resolveId(id) { if(id==='/src/growth-fit-fixture.tsx') return fixtureId; },
      load(id) {
        if(id!==fixtureId) return;
        return `
          import React, {useEffect} from 'react';
          import {createRoot} from 'react-dom/client';
          import {usePhageStore} from '@phage-explorer/state';
          import SimulationView from './components/SimulationView';
          import {OverlayProvider,useOverlay} from './components/overlays/OverlayProvider';
          import {ToastProvider} from './components/ui/Toast';
          import {ScrollProvider} from './providers';
          import {getOrchestrator} from './workers/ComputeOrchestrator';
          import './styles/index.css';
          usePhageStore.setState({currentPhage:null});
          const service=getOrchestrator(), step=service.stepSimulation.bind(service);
          window.forwardSteps=0;
          service.stepSimulation=(...args)=>{window.forwardSteps++;return step(...args);};
          function Fixture() {
            const {open,setOverlayData}=useOverlay();
            useEffect(()=>{setOverlayData('simulationView.simId','infection-kinetics');open('simulationView');},[]);
            return <SimulationView/>;
          }
          createRoot(document.getElementById('root')).render(<ScrollProvider><ToastProvider><OverlayProvider><Fixture/></OverlayProvider></ToastProvider></ScrollProvider>);
        `;
      },
      configureServer(vite) {
        vite.middlewares.use('/growth-fit-fixture',(_request,response,next)=>{
          void vite.transformIndexHtml('/growth-fit-fixture','<div id="root"></div><script type="module" src="/src/growth-fit-fixture.tsx"></script>')
            .then(html=>{response.setHeader('Content-Type','text/html');response.end(html);}).catch(next);
        });
      },
    }],
  } satisfies InlineConfig));
  const errors:string[]=[], requests:Array<{url:string;method:string;body:string|null}>=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>requests.push({url:request.url(),method:request.method(),body:request.postData()}));
  let releaseWorker: (()=>void) | undefined;
  try {
    await server.listen();
    await page.goto(`${server.resolvedUrls!.local[0]}growth-fit-fixture`);
    const overlay=page.getByTestId('overlay-simulationView');
    const panel=page.getByRole('region',{name:'Experimental growth inference',exact:true});
    await overlay.getByRole('button',{name:'Experimental growth fit',exact:true}).click();
    await expect(panel).toBeVisible();
    // Let an already scheduled forward callback settle, then verify no background simulation is scheduled.
    await page.waitForTimeout(100);
    const forward=await page.evaluate(()=>(window as unknown as {forwardSteps:number}).forwardSteps);
    await page.waitForTimeout(200);
    expect(await page.evaluate(()=>(window as unknown as {forwardSteps:number}).forwardSteps)).toBe(forward);
    await panel.getByLabel('Fixed bacterial growth rate /min',{exact:true}).fill('.005');
    await panel.getByLabel('Fixed phage decay rate /min',{exact:true}).fill('.002');
    await panel.getByLabel('Fixed infected-stage count',{exact:true}).fill('3');
    const input=panel.getByLabel('Import growth CSV, TSV, dataset JSON or saved fit',{exact:true});
    const load=(content:string,name='private-growth-fixture.csv')=>input.setInputFiles({name,mimeType:'text/plain',buffer:Buffer.from(content)});
    await load(CSV);
    await expect(panel.getByTestId('growth-status')).toContainText('Data loaded.');
    await expect(panel.getByTestId('growth-result')).toHaveCount(0);
    await panel.getByLabel('Adsorption rate (mL/PFU/min)',{exact:true}).fill('1e-9');
    await panel.getByLabel('Mean infection-to-lysis time (min)',{exact:true}).fill('32');
    await panel.getByLabel('Burst yield (PFU/cell)',{exact:true}).fill('55');
    await panel.getByLabel('Fit initialization seed',{exact:true}).fill('0');
    await panel.getByRole('checkbox',{name:'I have checked the fixed conditions, measurement definitions and supplied observation SDs.',exact:true}).check();
    await panel.getByRole('button',{name:'Fit experimental growth data',exact:true}).click();
    const result=panel.getByTestId('growth-result');
    await expect(result).toBeVisible();
    await expect(result).toContainText('Sensitivity rank: 3/3');
    const exported=async()=>{
      const downloading=page.waitForEvent('download');
      await panel.getByRole('button',{name:'Export accepted growth fit',exact:true}).click();
      return readFile((await (await downloading).path())!,'utf8');
    };
    const content=await exported(),record=await parseAnalysisRecord(content);
    const estimates=record.fields.estimates.value as Record<string,{value:number;status:string}>;
    for(const [key,truth] of Object.entries({adsorptionRate:2e-9,latentPeriod:20,burstSize:35})) {
      expect(Math.abs(estimates[key].value/truth-1),key).toBeLessThan(2e-5);
      expect(estimates[key].status,key).toBe('locally-estimable');
    }
    await panel.getByLabel('Displayed growth measurement',{exact:true}).selectOption('CFU');
    await expect(panel.getByRole('img',{name:'Observed and fitted CFU growth curve',exact:true})).toBeVisible();
    await expect(panel.getByRole('table',{name:'Growth observations and residuals',exact:true}).locator('tbody tr')).toHaveCount(12);
    await panel.getByLabel('Fit initialization seed',{exact:true}).fill('77');
    expect((await parseAnalysisRecord(await exported())).resultId).toBe(record.resultId);

    // Full page reload removes all in-memory fit state, then replay uses the real worker.
    await page.reload();
    await overlay.getByRole('button',{name:'Experimental growth fit',exact:true}).click();
    await load(content,'saved-growth.json');
    await expect(panel.getByTestId('growth-status')).toContainText('Verified: fresh fit');
    await expect(result).toHaveAttribute('data-result-id',record.resultId);
    await expect(panel.getByLabel('Fit initialization seed',{exact:true})).toHaveValue('0');
    expect((await parseAnalysisRecord(await exported())).resultId).toBe(record.resultId);
    const forged=await parseAnalysisRecord(content);
    (forged.fields.estimates.value as Record<string,AnalysisJson>).burstSize={value:999,status:'locally-estimable',interval95:[998,1000]};
    const resigned=await createAnalysisRecord({...forged,inputs:forged.inputs.map(({sha256:_sha,...value})=>value)});
    await load(serializeAnalysisRecord(resigned),'forged-growth.json');
    await expect(panel.getByRole('alert')).toContainText('Fresh growth fit differs');
    await expect(result).toHaveAttribute('data-result-id',record.resultId);

    // A delayed actual worker module load, not a fake numeric response.
    let requested=false;
    const gate=new Promise<void>(resolve=>{releaseWorker=resolve;});
    await page.route(/growth-inference\.worker\.ts/,async route=>{requested=true;await gate;await route.continue().catch(()=>{});});
    await load(content,'cancelled-growth.json');
    await expect.poll(()=>requested).toBe(true);
    await panel.getByRole('button',{name:'Cancel growth work',exact:true}).click();
    releaseWorker?.();
    await expect(panel.getByTestId('growth-status')).toContainText('Growth work cancelled');
    await expect(result).toHaveAttribute('data-result-id',record.resultId);
    await page.unroute(/growth-inference\.worker\.ts/);
    await load(CSV.replace('100000,.03','0,.03'),'censored.csv');
    await expect(panel.getByRole('alert')).toContainText('censored');
    await expect(result).toHaveAttribute('data-result-id',record.resultId);
    expect(requests.some(request=>request.method!=='GET'&&request.method!=='HEAD')).toBe(false);
    expect(requests.some(request=>`${request.url} ${request.body??''}`.includes('private-growth-fixture'))).toBe(false);
    expect(errors).toEqual([]);
  } finally { releaseWorker?.();await server.close(); }
});
